### ISSUE TITLE
Issue building on Debian 8 / Jessie

### ISSUE THREAD

**Issue by bdamer** [kinumi/sk98lin#2]
First of all, thanks for updating the driver - I wasted too many hours today trying to get the original to compile on Debian 8!

I am using the following environment: 

```
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
```

Following your instructions, I found that I had to make some minor adjustments on my machine to get it to work. The install script was complaining about not being able to find the kernel headers, despite the package being installed. I guess some of the paths have change in recent version. I made the following changes:

```
ln -s /usr/src/linux-headers-$(uname -r) /usr/src/linux
mkdir /usr/src/linux/include/linux
ln -s /usr/src/linux/include/generated/autoconf.h /usr/src/linux/include/linux/autoconf.h
```

Not sure if there is a good way to handle these changes in the install script, but maybe you'll want to include them as part of the documentation.

**Comment by kinumi** [comment]
Thank you @bdamer !
This issue would be useful for someone.
I don't have an environment to verify, so i cannot update both script or document.
