### ISSUE TITLE
when i build on ubuntu12 shows sky2.c:2023:8: error: struct sk_buff has no member named hash

### ISSUE THREAD

**Issue by itsgoodtobebad** [kinumi/sk98lin#3]
thx a lot for the software.
I install this driver on ubuntu12 but an error occurs:
sky2.c: In function HandleReceives:
sky2.c:2023:8: error: struct sk_buff has no member named hash

can this driver use on ubuntu12?

**Comment by kinumi** [comment]
@itsgoodtobebad,

Ubuntu12.04's kernel version is 3.2.

I tested this driver on only kernel version 3.16 or 3.19.
If you can update kernel version to 3.16 or 3.19, you can use this.
